import { access, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { execa } from "execa";
import { EXIT } from "./cli-error.js";

export type AgentKind = "claude-code" | "codex";

export type InitOptions = {
  cwd: string;
  detectClaude?: () => Promise<boolean>;
  detectCodex?: () => Promise<boolean>;
  write?: (text: string) => void;
};

const GITIGNORE_LINES = [".canaryfile/runs/", ".canaryfile/worktrees/"];

async function binaryExists(file: string, args: string[]): Promise<boolean> {
  try {
    await execa(file, args, { timeout: 10_000, reject: false });
    return true;
  } catch {
    return false;
  }
}

function yamlTemplate(adapter: AgentKind): string {
  return `# Generated by \`canaryfile init\`. Replace the example prompts and
# verifiers, then run \`canaryfile record\` and commit the snapshot.
version: 1

agent:
  adapter: ${adapter}          # claude-code | codex | custom
  model: default                # "default" = the agent's configured model
  timeout: 300s
  # command: "your-agent --prompt {{prompt}}"  # custom adapter only

defaults:
  runs: 5
  budget: 0.50

tasks:
  - name: example-bugfix
    prompt: |
      Find a real bug in this repository and fix it.
      Keep the change as small as possible.
    verify:
      - run: echo ok
    tags: [smoke]

  - name: example-feature
    prompt: |
      Add a small, testable improvement to this repository.
    verify:
      - run: echo ok
    tags: [smoke]
`;
}

function hasIgnoreLine(content: string, line: string): boolean {
  const variants = new Set([line, `**/${line}`]);
  return content.split(/\r?\n/).some((entry) => variants.has(entry.trim()));
}

async function pathExists(target: string): Promise<boolean> {
  try {
    await access(target);
    return true;
  } catch {
    return false;
  }
}

async function ensureGitignore(dir: string): Promise<{
  gitignorePath: string;
  appended: boolean;
}> {
  const gitignorePath = path.join(dir, ".gitignore");
  const existing = (await pathExists(gitignorePath))
    ? await readFile(gitignorePath, "utf8")
    : "";
  const missing = GITIGNORE_LINES.filter((line) => !hasIgnoreLine(existing, line));
  if (missing.length === 0) {
    return { gitignorePath, appended: false };
  }
  const prefix =
    existing.length === 0 || existing.endsWith("\n") ? "" : "\n";
  await writeFile(gitignorePath, `${existing}${prefix}${missing.join("\n")}\n`, "utf8");
  return { gitignorePath, appended: true };
}

export async function initCanaryfile(options: InitOptions): Promise<number> {
  const write = options.write ?? ((text) => process.stdout.write(`${text}\n`));
  const detectClaude =
    options.detectClaude ?? (() => binaryExists("claude", ["-v"]));
  const detectCodex =
    options.detectCodex ?? (() => binaryExists("codex", ["--version"]));

  const adapter: AgentKind = (await detectClaude())
    ? "claude-code"
    : (await detectCodex())
      ? "codex"
      : "claude-code";

  const yamlPath = path.join(options.cwd, "canaryfile.yaml");
  const createdYaml = !(await pathExists(yamlPath));
  if (createdYaml) {
    await writeFile(yamlPath, yamlTemplate(adapter), "utf8");
    write(`wrote canaryfile.yaml (adapter: ${adapter})`);
  } else {
    write("canaryfile.yaml already exists");
  }

  const gitignore = await ensureGitignore(options.cwd);
  if (gitignore.appended) {
    write("updated .gitignore for .canaryfile/runs/ and worktrees");
  } else {
    write(".gitignore already ignores canaryfile run artifacts");
  }

  return EXIT.ok;
}
